name: 'Get role-session-name'
description: 'Produce valid role-session-name from `github` context. For use by `aws-actions/configure-aws-credentials`'
outputs:
  role-session-name:
    description: 'Role session name'
runs:
  using: 'node16'
  main: 'dist/index.js'
